In [1]:
import numpy as np
import pandas as pd

In [2]:
data = np.array([[3, 7],
                 [-4, -6],
                 [1, -1],
                 [7, 8],
                 [-4, -1],
                 [-3, -7]])

In [3]:
dataframe = pd.DataFrame(data, columns=['x1', 'x2'])

Standard Normal Form: If it contains mean as 0 and standard deviation as 1

In [4]:
dataframe

,x1,x2
0,3,7
1,-4,-6
2,1,-1
3,7,8
4,-4,-1
5,-3,-7


In [6]:
dataframe.describe()

,x1,x2
count,6.000000,6.000000
mean,0.000000,0.000000
std,4.472136,6.324555
min,-4.000000,-7.000000
25%,-3.750000,-4.750000
50%,-1.000000,-1.000000
75%,2.500000,5.000000
max,7.000000,8.000000


In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
dataScaled = scaler.fit_transform(dataframe)

In [9]:
type(dataScaled)

numpy.ndarray

In [10]:
dataframe = pd.DataFrame(dataScaled, columns=['x1', 'x2'])

In [11]:
dataframe.describe()

,x1,x2
count,6.000000e+00,6.000000
mean,1.850372e-17,0.000000
std,1.095445e+00,1.095445
min,-9.797959e-01,-1.212436
25%,-9.185587e-01,-0.822724
50%,-2.449490e-01,-0.173205
75%,6.123724e-01,0.866025
max,1.714643e+00,1.385641


1. To check whether the data is in standard normal form or not. As our data is in standard normal form, we are skipping that step of coverting our data to standard normal form.

2. Covariance Matrix between the two features that we have (x1, x2)

In [12]:
## Approach 1
c1 = dataframe.x1
c2 = dataframe.x2
np.cov(c1, c2)

array([[1.2       , 1.06066017],
       [1.06066017, 1.2       ]])

In [13]:
dataframe.shape

(6, 2)

In [14]:
## Approach 2
covarianceMatrix = dataframe.T @ dataframe / 5
covarianceMatrix

,x1,x2
x1,1.20000,1.06066
x2,1.06066,1.20000


In [15]:
## Approach 3
np.sum(c1 * c2)/5

1.0606601717798212

3. Evaluate the eigen values and eigen vectors of the above coorelation matrix

In [16]:
eigenValues, eigenVectors = np.linalg.eig(covarianceMatrix)

In [17]:
## eigenValues = # features
## eigenValue represents the strength of the information given by the eigenVector
eigenValues

array([2.26066017, 0.13933983])

In [18]:
eigenVectors

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [19]:
eigenVectors[:, 0]

array([0.70710678, 0.70710678])

In [20]:
dataframe

,x1,x2
0,0.734847,1.212436
1,-0.979796,-1.039230
2,0.244949,-0.173205
3,1.714643,1.385641
4,-0.979796,-0.173205
5,-0.734847,-1.212436


In [21]:
## PC1 - Contains the maximum information of the original two features that you have
PC1 = dataframe @ eigenVectors[:, 0]

In [22]:
PC1

0    1.376937
1   -1.427667
2    0.050731
3    2.192231
4   -0.815295
5   -1.376937
dtype: float64

In [23]:
## PC2
PC2 = dataframe @ eigenVectors[:, 1]
PC2

0    0.337706
1   -0.042027
2   -0.295680
3   -0.232640
4    0.570346
5   -0.337706
dtype: float64

In [24]:
dataframe

,x1,x2
0,0.734847,1.212436
1,-0.979796,-1.039230
2,0.244949,-0.173205
3,1.714643,1.385641
4,-0.979796,-0.173205
5,-0.734847,-1.212436
